server:
  port: 3030
  servlet:
    context-path: /SpringBootCRUDApp
---
spring:
  profiles: prod
datasource:
  tdptestapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    com.ege: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /Users/esahan/logs/application.log       
  
client-oauth:
 secret: egepwd 
 user: ege  
---
spring:
  profiles: local,default
datasource:
  tdptestapp:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr
    driverClassName: oracle.jdbc.driver.OracleDriver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: validate
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.Oracle12cDialect
      
logging:
  level:
#    org.springframework.web: ERROR
    org.springframework.security: DEBUG
    com.ege: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /Users/esahan/log/application.log    
   
client-oauth:
 secret: egepwd 
 user: ege
---
spring:
  profiles: alper    
datasource:
  tdptestapp:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: TDP
    password: TDP
    driverClassName: oracle.jdbc.driver.OracleDriver
    defaultSchema:
    maxPoolSize: 20
    mapping-resources: db/mappings/alper.xml
    hibernate:
      hbm2ddl.method: create
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.Oracle10gDialect
      
logging:
  level:
#    org.springframework.web: ERROR
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /log/application.log    
   
client-oauth:
 secret: egepwd 
 user: ege